version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  yacyproto:
    in:
      - .
      - "**"

vendors:
  yacymodel:
    in:
      - github.com/D4rk4/yago/yacymodel
      - github.com/D4rk4/yago/yacymodel/**

deps:
  yacyproto:
    mayDependOn:
      - yacyproto
    canUse:
      - yacymodel
