package yagonode

import "strings"

func composeNodeConfig(in nodeConfigComposition) nodeConfig {
	return nodeConfig{
		Hash:                         in.network.hash,
		NetworkName:                  in.networkName,
		Name:                         in.peerName,
		DataDir:                      in.data.directory,
		AdvertiseHost:                in.network.advertisement.host,
		AdvertisePort:                in.network.advertisement.port,
		AdvertisePortPinned:          in.network.advertisement.portPinned,
		PublicSelfTestURL:            in.network.advertisement.selfTestURL,
		SelfTestURLPinned:            in.network.advertisement.selfTestPinned,
		PeerAddr:                     in.network.peerAddress,
		OpsAddr:                      envWithDefault(in.getenv, envOpsAddr, defaultOpsAddr),
		PublicAddr:                   publicListenerAddr(in.getenv),
		StoragePath:                  in.data.databasePath,
		SearchIndexPath:              in.data.searchIndexPath,
		StorageQuotaByte:             in.data.quotaByte,
		StorageReservedFreeBytes:     in.data.reservedFreeBytes,
		StoragePressureRecoveryBytes: in.data.pressureRecoveryBytes,
		StorageCompaction:            in.data.compaction,
		StorageReadDefer:             in.data.readDefer,
		StorageAutosplit:             in.derived.storageAutosplit,
		StorageDeferFsync:            in.derived.storageDeferFsync,
		TrustedProxies:               in.trustedProxies,
		EgressAllowLAN:               in.egressAllowLAN,
		EgressAllowedCIDRs:           in.egressAllowedCIDRs,
		SeedlistURLs:                 in.network.seedlistURLs,
		AnnounceInterval:             in.network.announceInterval,
		GreetsPerCycle:               in.network.greetsPerCycle,
		SearchAPIKey:                 strings.TrimSpace(in.getenv(envSearchAccessToken)),
		SearchRequireAPIKey:          in.derived.requireAPIKey,
		PublicSearchUIEnabled:        in.derived.publicSearchUI,
		SearchLinksNewTab:            in.derived.searchLinksNewTab,
		SearchClickCapture:           in.derived.searchClickCapture,
		HTTPSRedirect:                in.derived.httpsRedirect,
		PublicBaseURL:                in.derived.publicBaseURL,
		QueryLogMode:                 in.derived.queryLogMode,
		MetricsEnabled:               in.derived.metricsEnabled,
		LoggingLevel:                 in.derived.loggingLevel,
		AdminRestartEnabled:          in.derived.adminRestartEnabled,
		IndexRemoteResults:           in.derived.indexRemoteResults,
		SwarmMorphology:              in.derived.swarmMorphology,
		PeerSnippetFetch:             in.derived.peerSnippetFetch,
		RemotePeerTimeout:            in.derived.remotePeerTimeout,
		RemoteTimeout:                in.derived.remoteTimeout,
		NetworkAuthenticationMode:    in.networkAuthentication.mode,
		NetworkAuthenticationSecret:  in.networkAuthentication.secret,
		LANDiscovery:                 in.derived.lanDiscovery,
		PeerHTTPSPreferred:           in.derived.peerHTTPSPreferred,
		SwarmSeed:                    in.derived.swarmSeed,
		AutocrawlerCrawl:             defaultSeedCrawlOptions(),
		DeclaredBirthDate:            in.derived.birthDate,
		DHT:                          in.derived.dht,
		WebFallback:                  in.derived.webFallback,
		ExtractFetch:                 in.derived.extractFetch,
		RemoteCrawl:                  in.remoteCrawl,
	}
}
