version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  yacycrawlcontract:
    in:
      - .
      - "**"

vendors:
  yacymodel:
    in:
      - github.com/D4rk4/yago/yacymodel
      - github.com/D4rk4/yago/yacymodel/**
  grpc:
    in:
      - google.golang.org/grpc
      - google.golang.org/grpc/**
  protobuf:
    in:
      - google.golang.org/protobuf
      - google.golang.org/protobuf/**

deps:
  yacycrawlcontract:
    mayDependOn:
      - yacycrawlcontract
    canUse:
      - yacymodel
      - grpc
      - protobuf
