// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: crawlexchange.proto

package crawlrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrawlExchange_StreamOrders_FullMethodName = "/yacycrawl.v1.CrawlExchange/StreamOrders"
	CrawlExchange_AckOrder_FullMethodName     = "/yacycrawl.v1.CrawlExchange/AckOrder"
	CrawlExchange_Heartbeat_FullMethodName    = "/yacycrawl.v1.CrawlExchange/Heartbeat"
	CrawlExchange_SubmitIngest_FullMethodName = "/yacycrawl.v1.CrawlExchange/SubmitIngest"
)

// CrawlExchangeClient is the client API for CrawlExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrawlExchange is the node<->crawler control plane. The node is the server and
// owns a durable order queue; crawlers are clients that stream claimed orders
// and submit ingest batches back. Payloads carry the JSON encodings produced by
// the contract's MarshalCrawlOrder and MarshalIngestBatch codecs, so the wire
// service is stable while the crawl data model stays authoritative in Go.
type CrawlExchangeClient interface {
	// StreamOrders delivers claimed crawl orders to one crawler as they become
	// available. Each order is leased to the receiving worker: the node holds it
	// in a durable leased state, tagged with a lease id, until the worker acks it
	// or the lease expires, at which point it is redelivered.
	StreamOrders(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CrawlOrderMessage], error)
	// AckOrder settles a leased order: a plain ack deletes it, and an ack with
	// requeue returns it to the pending queue for another worker.
	AckOrder(ctx context.Context, in *OrderAck, opts ...grpc.CallOption) (*OrderAckResult, error)
	// Heartbeat extends the lease deadline on every order currently leased to the
	// worker, so a live worker keeps its in-flight orders from being redelivered.
	Heartbeat(ctx context.Context, in *WorkerHeartbeat, opts ...grpc.CallOption) (*WorkerHeartbeatResult, error)
	// SubmitIngest hands one ingest batch to the node and blocks until the node
	// absorbs it. The node returns an error when its ingest pipeline is saturated
	// so the crawler retries, which is the backpressure signal.
	SubmitIngest(ctx context.Context, in *IngestBatchMessage, opts ...grpc.CallOption) (*IngestAck, error)
}

type crawlExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlExchangeClient(cc grpc.ClientConnInterface) CrawlExchangeClient {
	return &crawlExchangeClient{cc}
}

func (c *crawlExchangeClient) StreamOrders(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CrawlOrderMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CrawlExchange_ServiceDesc.Streams[0], CrawlExchange_StreamOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerRegistration, CrawlOrderMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrawlExchange_StreamOrdersClient = grpc.ServerStreamingClient[CrawlOrderMessage]

func (c *crawlExchangeClient) AckOrder(ctx context.Context, in *OrderAck, opts ...grpc.CallOption) (*OrderAckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderAckResult)
	err := c.cc.Invoke(ctx, CrawlExchange_AckOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlExchangeClient) Heartbeat(ctx context.Context, in *WorkerHeartbeat, opts ...grpc.CallOption) (*WorkerHeartbeatResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerHeartbeatResult)
	err := c.cc.Invoke(ctx, CrawlExchange_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlExchangeClient) SubmitIngest(ctx context.Context, in *IngestBatchMessage, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, CrawlExchange_SubmitIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlExchangeServer is the server API for CrawlExchange service.
// All implementations must embed UnimplementedCrawlExchangeServer
// for forward compatibility.
//
// CrawlExchange is the node<->crawler control plane. The node is the server and
// owns a durable order queue; crawlers are clients that stream claimed orders
// and submit ingest batches back. Payloads carry the JSON encodings produced by
// the contract's MarshalCrawlOrder and MarshalIngestBatch codecs, so the wire
// service is stable while the crawl data model stays authoritative in Go.
type CrawlExchangeServer interface {
	// StreamOrders delivers claimed crawl orders to one crawler as they become
	// available. Each order is leased to the receiving worker: the node holds it
	// in a durable leased state, tagged with a lease id, until the worker acks it
	// or the lease expires, at which point it is redelivered.
	StreamOrders(*WorkerRegistration, grpc.ServerStreamingServer[CrawlOrderMessage]) error
	// AckOrder settles a leased order: a plain ack deletes it, and an ack with
	// requeue returns it to the pending queue for another worker.
	AckOrder(context.Context, *OrderAck) (*OrderAckResult, error)
	// Heartbeat extends the lease deadline on every order currently leased to the
	// worker, so a live worker keeps its in-flight orders from being redelivered.
	Heartbeat(context.Context, *WorkerHeartbeat) (*WorkerHeartbeatResult, error)
	// SubmitIngest hands one ingest batch to the node and blocks until the node
	// absorbs it. The node returns an error when its ingest pipeline is saturated
	// so the crawler retries, which is the backpressure signal.
	SubmitIngest(context.Context, *IngestBatchMessage) (*IngestAck, error)
	mustEmbedUnimplementedCrawlExchangeServer()
}

// UnimplementedCrawlExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrawlExchangeServer struct{}

func (UnimplementedCrawlExchangeServer) StreamOrders(*WorkerRegistration, grpc.ServerStreamingServer[CrawlOrderMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedCrawlExchangeServer) AckOrder(context.Context, *OrderAck) (*OrderAckResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckOrder not implemented")
}
func (UnimplementedCrawlExchangeServer) Heartbeat(context.Context, *WorkerHeartbeat) (*WorkerHeartbeatResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCrawlExchangeServer) SubmitIngest(context.Context, *IngestBatchMessage) (*IngestAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitIngest not implemented")
}
func (UnimplementedCrawlExchangeServer) mustEmbedUnimplementedCrawlExchangeServer() {}
func (UnimplementedCrawlExchangeServer) testEmbeddedByValue()                       {}

// UnsafeCrawlExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlExchangeServer will
// result in compilation errors.
type UnsafeCrawlExchangeServer interface {
	mustEmbedUnimplementedCrawlExchangeServer()
}

func RegisterCrawlExchangeServer(s grpc.ServiceRegistrar, srv CrawlExchangeServer) {
	// If the following call pancis, it indicates UnimplementedCrawlExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrawlExchange_ServiceDesc, srv)
}

func _CrawlExchange_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkerRegistration)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CrawlExchangeServer).StreamOrders(m, &grpc.GenericServerStream[WorkerRegistration, CrawlOrderMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CrawlExchange_StreamOrdersServer = grpc.ServerStreamingServer[CrawlOrderMessage]

func _CrawlExchange_AckOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlExchangeServer).AckOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlExchange_AckOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlExchangeServer).AckOrder(ctx, req.(*OrderAck))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlExchange_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlExchangeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlExchange_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlExchangeServer).Heartbeat(ctx, req.(*WorkerHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlExchange_SubmitIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlExchangeServer).SubmitIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlExchange_SubmitIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlExchangeServer).SubmitIngest(ctx, req.(*IngestBatchMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlExchange_ServiceDesc is the grpc.ServiceDesc for CrawlExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yacycrawl.v1.CrawlExchange",
	HandlerType: (*CrawlExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AckOrder",
			Handler:    _CrawlExchange_AckOrder_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CrawlExchange_Heartbeat_Handler,
		},
		{
			MethodName: "SubmitIngest",
			Handler:    _CrawlExchange_SubmitIngest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrders",
			Handler:       _CrawlExchange_StreamOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crawlexchange.proto",
}
