// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: crawlexchange.proto

package crawlrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CrawlControlKind is a directive the node pushes to a worker to steer a run it is
// executing: pause and resume gate fetching, cancel drains the run, and set_rate
// caps the fetch pace.
type CrawlControlKind int32

const (
	CrawlControlKind_CRAWL_CONTROL_KIND_UNSPECIFIED CrawlControlKind = 0
	CrawlControlKind_CRAWL_CONTROL_KIND_PAUSE       CrawlControlKind = 1
	CrawlControlKind_CRAWL_CONTROL_KIND_RESUME      CrawlControlKind = 2
	CrawlControlKind_CRAWL_CONTROL_KIND_CANCEL      CrawlControlKind = 3
	CrawlControlKind_CRAWL_CONTROL_KIND_SET_RATE    CrawlControlKind = 4
	// RESTART asks the whole worker to shut down gracefully so its supervisor
	// brings it back up; run_id is ignored.
	CrawlControlKind_CRAWL_CONTROL_KIND_RESTART                          CrawlControlKind = 5
	CrawlControlKind_CRAWL_CONTROL_KIND_SET_WORKERS                      CrawlControlKind = 6
	CrawlControlKind_CRAWL_CONTROL_KIND_SET_AUTOMATIC_DISCOVERY_PRIORITY CrawlControlKind = 7
)

// Enum value maps for CrawlControlKind.
var (
	CrawlControlKind_name = map[int32]string{
		0: "CRAWL_CONTROL_KIND_UNSPECIFIED",
		1: "CRAWL_CONTROL_KIND_PAUSE",
		2: "CRAWL_CONTROL_KIND_RESUME",
		3: "CRAWL_CONTROL_KIND_CANCEL",
		4: "CRAWL_CONTROL_KIND_SET_RATE",
		5: "CRAWL_CONTROL_KIND_RESTART",
		6: "CRAWL_CONTROL_KIND_SET_WORKERS",
		7: "CRAWL_CONTROL_KIND_SET_AUTOMATIC_DISCOVERY_PRIORITY",
	}
	CrawlControlKind_value = map[string]int32{
		"CRAWL_CONTROL_KIND_UNSPECIFIED":                      0,
		"CRAWL_CONTROL_KIND_PAUSE":                            1,
		"CRAWL_CONTROL_KIND_RESUME":                           2,
		"CRAWL_CONTROL_KIND_CANCEL":                           3,
		"CRAWL_CONTROL_KIND_SET_RATE":                         4,
		"CRAWL_CONTROL_KIND_RESTART":                          5,
		"CRAWL_CONTROL_KIND_SET_WORKERS":                      6,
		"CRAWL_CONTROL_KIND_SET_AUTOMATIC_DISCOVERY_PRIORITY": 7,
	}
)

func (x CrawlControlKind) Enum() *CrawlControlKind {
	p := new(CrawlControlKind)
	*p = x
	return p
}

func (x CrawlControlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrawlControlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_crawlexchange_proto_enumTypes[0].Descriptor()
}

func (CrawlControlKind) Type() protoreflect.EnumType {
	return &file_crawlexchange_proto_enumTypes[0]
}

func (x CrawlControlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrawlControlKind.Descriptor instead.
func (CrawlControlKind) EnumDescriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{0}
}

type CrawlRunState int32

const (
	CrawlRunState_CRAWL_RUN_STATE_UNSPECIFIED CrawlRunState = 0
	CrawlRunState_CRAWL_RUN_STATE_RUNNING     CrawlRunState = 1
	CrawlRunState_CRAWL_RUN_STATE_FINISHED    CrawlRunState = 2
	CrawlRunState_CRAWL_RUN_STATE_CANCELLED   CrawlRunState = 3
)

// Enum value maps for CrawlRunState.
var (
	CrawlRunState_name = map[int32]string{
		0: "CRAWL_RUN_STATE_UNSPECIFIED",
		1: "CRAWL_RUN_STATE_RUNNING",
		2: "CRAWL_RUN_STATE_FINISHED",
		3: "CRAWL_RUN_STATE_CANCELLED",
	}
	CrawlRunState_value = map[string]int32{
		"CRAWL_RUN_STATE_UNSPECIFIED": 0,
		"CRAWL_RUN_STATE_RUNNING":     1,
		"CRAWL_RUN_STATE_FINISHED":    2,
		"CRAWL_RUN_STATE_CANCELLED":   3,
	}
)

func (x CrawlRunState) Enum() *CrawlRunState {
	p := new(CrawlRunState)
	*p = x
	return p
}

func (x CrawlRunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrawlRunState) Descriptor() protoreflect.EnumDescriptor {
	return file_crawlexchange_proto_enumTypes[1].Descriptor()
}

func (CrawlRunState) Type() protoreflect.EnumType {
	return &file_crawlexchange_proto_enumTypes[1]
}

func (x CrawlRunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrawlRunState.Descriptor instead.
func (CrawlRunState) EnumDescriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{1}
}

type WorkerRegistration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerSessionId string                 `protobuf:"bytes,2,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_crawlexchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistration) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

type CrawlOrderMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderJson         []byte                 `protobuf:"bytes,1,opt,name=order_json,json=orderJson,proto3" json:"order_json,omitempty"`
	LeaseId           string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Recovered         bool                   `protobuf:"varint,3,opt,name=recovered,proto3" json:"recovered,omitempty"`
	RecoveredBatchEnd bool                   `protobuf:"varint,4,opt,name=recovered_batch_end,json=recoveredBatchEnd,proto3" json:"recovered_batch_end,omitempty"`
	RecoveredLeaseIds []string               `protobuf:"bytes,5,rep,name=recovered_lease_ids,json=recoveredLeaseIds,proto3" json:"recovered_lease_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrawlOrderMessage) Reset() {
	*x = CrawlOrderMessage{}
	mi := &file_crawlexchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlOrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlOrderMessage) ProtoMessage() {}

func (x *CrawlOrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlOrderMessage.ProtoReflect.Descriptor instead.
func (*CrawlOrderMessage) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlOrderMessage) GetOrderJson() []byte {
	if x != nil {
		return x.OrderJson
	}
	return nil
}

func (x *CrawlOrderMessage) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CrawlOrderMessage) GetRecovered() bool {
	if x != nil {
		return x.Recovered
	}
	return false
}

func (x *CrawlOrderMessage) GetRecoveredBatchEnd() bool {
	if x != nil {
		return x.RecoveredBatchEnd
	}
	return false
}

func (x *CrawlOrderMessage) GetRecoveredLeaseIds() []string {
	if x != nil {
		return x.RecoveredLeaseIds
	}
	return nil
}

type OrderAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaseId           string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Requeue           bool                   `protobuf:"varint,2,opt,name=requeue,proto3" json:"requeue,omitempty"`
	OrderIdentity     []byte                 `protobuf:"bytes,3,opt,name=order_identity,json=orderIdentity,proto3" json:"order_identity,omitempty"`
	WorkerId          string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TerminalState     CrawlRunState          `protobuf:"varint,5,opt,name=terminal_state,json=terminalState,proto3,enum=yacycrawl.v1.CrawlRunState" json:"terminal_state,omitempty"`
	TerminalTally     *CrawlRunTally         `protobuf:"bytes,6,opt,name=terminal_tally,json=terminalTally,proto3" json:"terminal_tally,omitempty"`
	PagesPerMinute    *uint32                `protobuf:"varint,7,opt,name=pages_per_minute,json=pagesPerMinute,proto3,oneof" json:"pages_per_minute,omitempty"`
	WorkerSessionId   string                 `protobuf:"bytes,8,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	ConfirmationToken []byte                 `protobuf:"bytes,9,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderAck) Reset() {
	*x = OrderAck{}
	mi := &file_crawlexchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAck) ProtoMessage() {}

func (x *OrderAck) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAck.ProtoReflect.Descriptor instead.
func (*OrderAck) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{2}
}

func (x *OrderAck) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *OrderAck) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

func (x *OrderAck) GetOrderIdentity() []byte {
	if x != nil {
		return x.OrderIdentity
	}
	return nil
}

func (x *OrderAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *OrderAck) GetTerminalState() CrawlRunState {
	if x != nil {
		return x.TerminalState
	}
	return CrawlRunState_CRAWL_RUN_STATE_UNSPECIFIED
}

func (x *OrderAck) GetTerminalTally() *CrawlRunTally {
	if x != nil {
		return x.TerminalTally
	}
	return nil
}

func (x *OrderAck) GetPagesPerMinute() uint32 {
	if x != nil && x.PagesPerMinute != nil {
		return *x.PagesPerMinute
	}
	return 0
}

func (x *OrderAck) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

func (x *OrderAck) GetConfirmationToken() []byte {
	if x != nil {
		return x.ConfirmationToken
	}
	return nil
}

type OrderAckResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfirmationToken []byte                 `protobuf:"bytes,1,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderAckResult) Reset() {
	*x = OrderAckResult{}
	mi := &file_crawlexchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAckResult) ProtoMessage() {}

func (x *OrderAckResult) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAckResult.ProtoReflect.Descriptor instead.
func (*OrderAckResult) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{3}
}

func (x *OrderAckResult) GetConfirmationToken() []byte {
	if x != nil {
		return x.ConfirmationToken
	}
	return nil
}

type WorkerHeartbeat struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	WorkerId                    string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveFetches               *uint32                `protobuf:"varint,2,opt,name=active_fetches,json=activeFetches,proto3,oneof" json:"active_fetches,omitempty"`
	AcknowledgedDirectiveIds    []uint64               `protobuf:"varint,3,rep,packed,name=acknowledged_directive_ids,json=acknowledgedDirectiveIds,proto3" json:"acknowledged_directive_ids,omitempty"`
	ActiveLeaseIds              []string               `protobuf:"bytes,4,rep,name=active_lease_ids,json=activeLeaseIds,proto3" json:"active_lease_ids,omitempty"`
	WorkerSessionId             string                 `protobuf:"bytes,5,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	StorageAvailableBytes       *uint64                `protobuf:"varint,6,opt,name=storage_available_bytes,json=storageAvailableBytes,proto3,oneof" json:"storage_available_bytes,omitempty"`
	StoragePressure             *bool                  `protobuf:"varint,7,opt,name=storage_pressure,json=storagePressure,proto3,oneof" json:"storage_pressure,omitempty"`
	StorageMeasurementAvailable *bool                  `protobuf:"varint,8,opt,name=storage_measurement_available,json=storageMeasurementAvailable,proto3,oneof" json:"storage_measurement_available,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_crawlexchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetActiveFetches() uint32 {
	if x != nil && x.ActiveFetches != nil {
		return *x.ActiveFetches
	}
	return 0
}

func (x *WorkerHeartbeat) GetAcknowledgedDirectiveIds() []uint64 {
	if x != nil {
		return x.AcknowledgedDirectiveIds
	}
	return nil
}

func (x *WorkerHeartbeat) GetActiveLeaseIds() []string {
	if x != nil {
		return x.ActiveLeaseIds
	}
	return nil
}

func (x *WorkerHeartbeat) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

func (x *WorkerHeartbeat) GetStorageAvailableBytes() uint64 {
	if x != nil && x.StorageAvailableBytes != nil {
		return *x.StorageAvailableBytes
	}
	return 0
}

func (x *WorkerHeartbeat) GetStoragePressure() bool {
	if x != nil && x.StoragePressure != nil {
		return *x.StoragePressure
	}
	return false
}

func (x *WorkerHeartbeat) GetStorageMeasurementAvailable() bool {
	if x != nil && x.StorageMeasurementAvailable != nil {
		return *x.StorageMeasurementAvailable
	}
	return false
}

// CrawlControlDirective steers one run identified by its provenance token, or the
// whole worker when run_id is empty. pages_per_minute carries the cap for
// set_rate directives and is ignored otherwise.
type CrawlControlDirective struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Kind                         CrawlControlKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=yacycrawl.v1.CrawlControlKind" json:"kind,omitempty"`
	RunId                        []byte                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PagesPerMinute               uint32                 `protobuf:"varint,3,opt,name=pages_per_minute,json=pagesPerMinute,proto3" json:"pages_per_minute,omitempty"`
	FetchWorkers                 uint32                 `protobuf:"varint,4,opt,name=fetch_workers,json=fetchWorkers,proto3" json:"fetch_workers,omitempty"`
	PrioritizeAutomaticDiscovery bool                   `protobuf:"varint,5,opt,name=prioritize_automatic_discovery,json=prioritizeAutomaticDiscovery,proto3" json:"prioritize_automatic_discovery,omitempty"`
	DirectiveId                  uint64                 `protobuf:"varint,6,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CrawlControlDirective) Reset() {
	*x = CrawlControlDirective{}
	mi := &file_crawlexchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlControlDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlControlDirective) ProtoMessage() {}

func (x *CrawlControlDirective) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlControlDirective.ProtoReflect.Descriptor instead.
func (*CrawlControlDirective) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{5}
}

func (x *CrawlControlDirective) GetKind() CrawlControlKind {
	if x != nil {
		return x.Kind
	}
	return CrawlControlKind_CRAWL_CONTROL_KIND_UNSPECIFIED
}

func (x *CrawlControlDirective) GetRunId() []byte {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *CrawlControlDirective) GetPagesPerMinute() uint32 {
	if x != nil {
		return x.PagesPerMinute
	}
	return 0
}

func (x *CrawlControlDirective) GetFetchWorkers() uint32 {
	if x != nil {
		return x.FetchWorkers
	}
	return 0
}

func (x *CrawlControlDirective) GetPrioritizeAutomaticDiscovery() bool {
	if x != nil {
		return x.PrioritizeAutomaticDiscovery
	}
	return false
}

func (x *CrawlControlDirective) GetDirectiveId() uint64 {
	if x != nil {
		return x.DirectiveId
	}
	return 0
}

type WorkerHeartbeatResult struct {
	state                          protoimpl.MessageState   `protogen:"open.v1"`
	Directives                     []*CrawlControlDirective `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	RenewedLeaseIds                []string                 `protobuf:"bytes,2,rep,name=renewed_lease_ids,json=renewedLeaseIds,proto3" json:"renewed_lease_ids,omitempty"`
	LeaseTtlMilliseconds           uint64                   `protobuf:"varint,3,opt,name=lease_ttl_milliseconds,json=leaseTtlMilliseconds,proto3" json:"lease_ttl_milliseconds,omitempty"`
	StorageReservedFreeBytes       *uint64                  `protobuf:"varint,4,opt,name=storage_reserved_free_bytes,json=storageReservedFreeBytes,proto3,oneof" json:"storage_reserved_free_bytes,omitempty"`
	StoragePressureHysteresisBytes *uint64                  `protobuf:"varint,5,opt,name=storage_pressure_hysteresis_bytes,json=storagePressureHysteresisBytes,proto3,oneof" json:"storage_pressure_hysteresis_bytes,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *WorkerHeartbeatResult) Reset() {
	*x = WorkerHeartbeatResult{}
	mi := &file_crawlexchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeatResult) ProtoMessage() {}

func (x *WorkerHeartbeatResult) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeatResult.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeatResult) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerHeartbeatResult) GetDirectives() []*CrawlControlDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *WorkerHeartbeatResult) GetRenewedLeaseIds() []string {
	if x != nil {
		return x.RenewedLeaseIds
	}
	return nil
}

func (x *WorkerHeartbeatResult) GetLeaseTtlMilliseconds() uint64 {
	if x != nil {
		return x.LeaseTtlMilliseconds
	}
	return 0
}

func (x *WorkerHeartbeatResult) GetStorageReservedFreeBytes() uint64 {
	if x != nil && x.StorageReservedFreeBytes != nil {
		return *x.StorageReservedFreeBytes
	}
	return 0
}

func (x *WorkerHeartbeatResult) GetStoragePressureHysteresisBytes() uint64 {
	if x != nil && x.StoragePressureHysteresisBytes != nil {
		return *x.StoragePressureHysteresisBytes
	}
	return 0
}

type IngestBatchMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BatchJson       []byte                 `protobuf:"bytes,1,opt,name=batch_json,json=batchJson,proto3" json:"batch_json,omitempty"`
	LeaseId         string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerSessionId string                 `protobuf:"bytes,4,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestBatchMessage) Reset() {
	*x = IngestBatchMessage{}
	mi := &file_crawlexchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchMessage) ProtoMessage() {}

func (x *IngestBatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchMessage.ProtoReflect.Descriptor instead.
func (*IngestBatchMessage) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{7}
}

func (x *IngestBatchMessage) GetBatchJson() []byte {
	if x != nil {
		return x.BatchJson
	}
	return nil
}

func (x *IngestBatchMessage) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *IngestBatchMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *IngestBatchMessage) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_crawlexchange_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{8}
}

type CrawlRunTally struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fetched       uint64                 `protobuf:"varint,1,opt,name=fetched,proto3" json:"fetched,omitempty"`
	Indexed       uint64                 `protobuf:"varint,2,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Failed        uint64                 `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	RobotsDenied  uint64                 `protobuf:"varint,4,opt,name=robots_denied,json=robotsDenied,proto3" json:"robots_denied,omitempty"`
	Duplicates    uint64                 `protobuf:"varint,5,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	Pending       uint64                 `protobuf:"varint,6,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlRunTally) Reset() {
	*x = CrawlRunTally{}
	mi := &file_crawlexchange_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlRunTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlRunTally) ProtoMessage() {}

func (x *CrawlRunTally) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlRunTally.ProtoReflect.Descriptor instead.
func (*CrawlRunTally) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{9}
}

func (x *CrawlRunTally) GetFetched() uint64 {
	if x != nil {
		return x.Fetched
	}
	return 0
}

func (x *CrawlRunTally) GetIndexed() uint64 {
	if x != nil {
		return x.Indexed
	}
	return 0
}

func (x *CrawlRunTally) GetFailed() uint64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *CrawlRunTally) GetRobotsDenied() uint64 {
	if x != nil {
		return x.RobotsDenied
	}
	return 0
}

func (x *CrawlRunTally) GetDuplicates() uint64 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

func (x *CrawlRunTally) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type CrawlProgressReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunId           []byte                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ProfileHandle   string                 `protobuf:"bytes,3,opt,name=profile_handle,json=profileHandle,proto3" json:"profile_handle,omitempty"`
	ProfileName     string                 `protobuf:"bytes,4,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	State           CrawlRunState          `protobuf:"varint,5,opt,name=state,proto3,enum=yacycrawl.v1.CrawlRunState" json:"state,omitempty"`
	Tally           *CrawlRunTally         `protobuf:"bytes,6,opt,name=tally,proto3" json:"tally,omitempty"`
	PagesPerMinute  *uint32                `protobuf:"varint,7,opt,name=pages_per_minute,json=pagesPerMinute,proto3,oneof" json:"pages_per_minute,omitempty"`
	LeaseId         string                 `protobuf:"bytes,8,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	WorkerSessionId string                 `protobuf:"bytes,9,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CrawlProgressReport) Reset() {
	*x = CrawlProgressReport{}
	mi := &file_crawlexchange_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlProgressReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlProgressReport) ProtoMessage() {}

func (x *CrawlProgressReport) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlProgressReport.ProtoReflect.Descriptor instead.
func (*CrawlProgressReport) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{10}
}

func (x *CrawlProgressReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CrawlProgressReport) GetRunId() []byte {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *CrawlProgressReport) GetProfileHandle() string {
	if x != nil {
		return x.ProfileHandle
	}
	return ""
}

func (x *CrawlProgressReport) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *CrawlProgressReport) GetState() CrawlRunState {
	if x != nil {
		return x.State
	}
	return CrawlRunState_CRAWL_RUN_STATE_UNSPECIFIED
}

func (x *CrawlProgressReport) GetTally() *CrawlRunTally {
	if x != nil {
		return x.Tally
	}
	return nil
}

func (x *CrawlProgressReport) GetPagesPerMinute() uint32 {
	if x != nil && x.PagesPerMinute != nil {
		return *x.PagesPerMinute
	}
	return 0
}

func (x *CrawlProgressReport) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CrawlProgressReport) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

type CrawlProgressAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlProgressAck) Reset() {
	*x = CrawlProgressAck{}
	mi := &file_crawlexchange_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlProgressAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlProgressAck) ProtoMessage() {}

func (x *CrawlProgressAck) ProtoReflect() protoreflect.Message {
	mi := &file_crawlexchange_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlProgressAck.ProtoReflect.Descriptor instead.
func (*CrawlProgressAck) Descriptor() ([]byte, []int) {
	return file_crawlexchange_proto_rawDescGZIP(), []int{11}
}

var File_crawlexchange_proto protoreflect.FileDescriptor

const file_crawlexchange_proto_rawDesc = "" +
	"\n" +
	"\x13crawlexchange.proto\x12\fyacycrawl.v1\"]\n" +
	"\x12WorkerRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x11worker_session_id\x18\x02 \x01(\tR\x0fworkerSessionId\"\xcb\x01\n" +
	"\x11CrawlOrderMessage\x12\x1d\n" +
	"\n" +
	"order_json\x18\x01 \x01(\fR\torderJson\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1c\n" +
	"\trecovered\x18\x03 \x01(\bR\trecovered\x12.\n" +
	"\x13recovered_batch_end\x18\x04 \x01(\bR\x11recoveredBatchEnd\x12.\n" +
	"\x13recovered_lease_ids\x18\x05 \x03(\tR\x11recoveredLeaseIds\"\xaa\x03\n" +
	"\bOrderAck\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x18\n" +
	"\arequeue\x18\x02 \x01(\bR\arequeue\x12%\n" +
	"\x0eorder_identity\x18\x03 \x01(\fR\rorderIdentity\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12B\n" +
	"\x0eterminal_state\x18\x05 \x01(\x0e2\x1b.yacycrawl.v1.CrawlRunStateR\rterminalState\x12B\n" +
	"\x0eterminal_tally\x18\x06 \x01(\v2\x1b.yacycrawl.v1.CrawlRunTallyR\rterminalTally\x12-\n" +
	"\x10pages_per_minute\x18\a \x01(\rH\x00R\x0epagesPerMinute\x88\x01\x01\x12*\n" +
	"\x11worker_session_id\x18\b \x01(\tR\x0fworkerSessionId\x12-\n" +
	"\x12confirmation_token\x18\t \x01(\fR\x11confirmationTokenB\x13\n" +
	"\x11_pages_per_minute\"?\n" +
	"\x0eOrderAckResult\x12-\n" +
	"\x12confirmation_token\x18\x01 \x01(\fR\x11confirmationToken\"\x8a\x04\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x0eactive_fetches\x18\x02 \x01(\rH\x00R\ractiveFetches\x88\x01\x01\x12<\n" +
	"\x1aacknowledged_directive_ids\x18\x03 \x03(\x04R\x18acknowledgedDirectiveIds\x12(\n" +
	"\x10active_lease_ids\x18\x04 \x03(\tR\x0eactiveLeaseIds\x12*\n" +
	"\x11worker_session_id\x18\x05 \x01(\tR\x0fworkerSessionId\x12;\n" +
	"\x17storage_available_bytes\x18\x06 \x01(\x04H\x01R\x15storageAvailableBytes\x88\x01\x01\x12.\n" +
	"\x10storage_pressure\x18\a \x01(\bH\x02R\x0fstoragePressure\x88\x01\x01\x12G\n" +
	"\x1dstorage_measurement_available\x18\b \x01(\bH\x03R\x1bstorageMeasurementAvailable\x88\x01\x01B\x11\n" +
	"\x0f_active_fetchesB\x1a\n" +
	"\x18_storage_available_bytesB\x13\n" +
	"\x11_storage_pressureB \n" +
	"\x1e_storage_measurement_available\"\x9a\x02\n" +
	"\x15CrawlControlDirective\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.yacycrawl.v1.CrawlControlKindR\x04kind\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\fR\x05runId\x12(\n" +
	"\x10pages_per_minute\x18\x03 \x01(\rR\x0epagesPerMinute\x12#\n" +
	"\rfetch_workers\x18\x04 \x01(\rR\ffetchWorkers\x12D\n" +
	"\x1eprioritize_automatic_discovery\x18\x05 \x01(\bR\x1cprioritizeAutomaticDiscovery\x12!\n" +
	"\fdirective_id\x18\x06 \x01(\x04R\vdirectiveId\"\x98\x03\n" +
	"\x15WorkerHeartbeatResult\x12C\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2#.yacycrawl.v1.CrawlControlDirectiveR\n" +
	"directives\x12*\n" +
	"\x11renewed_lease_ids\x18\x02 \x03(\tR\x0frenewedLeaseIds\x124\n" +
	"\x16lease_ttl_milliseconds\x18\x03 \x01(\x04R\x14leaseTtlMilliseconds\x12B\n" +
	"\x1bstorage_reserved_free_bytes\x18\x04 \x01(\x04H\x00R\x18storageReservedFreeBytes\x88\x01\x01\x12N\n" +
	"!storage_pressure_hysteresis_bytes\x18\x05 \x01(\x04H\x01R\x1estoragePressureHysteresisBytes\x88\x01\x01B\x1e\n" +
	"\x1c_storage_reserved_free_bytesB$\n" +
	"\"_storage_pressure_hysteresis_bytes\"\x97\x01\n" +
	"\x12IngestBatchMessage\x12\x1d\n" +
	"\n" +
	"batch_json\x18\x01 \x01(\fR\tbatchJson\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12*\n" +
	"\x11worker_session_id\x18\x04 \x01(\tR\x0fworkerSessionId\"\v\n" +
	"\tIngestAck\"\xba\x01\n" +
	"\rCrawlRunTally\x12\x18\n" +
	"\afetched\x18\x01 \x01(\x04R\afetched\x12\x18\n" +
	"\aindexed\x18\x02 \x01(\x04R\aindexed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x04R\x06failed\x12#\n" +
	"\rrobots_denied\x18\x04 \x01(\x04R\frobotsDenied\x12\x1e\n" +
	"\n" +
	"duplicates\x18\x05 \x01(\x04R\n" +
	"duplicates\x12\x18\n" +
	"\apending\x18\x06 \x01(\x04R\apending\"\x84\x03\n" +
	"\x13CrawlProgressReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\fR\x05runId\x12%\n" +
	"\x0eprofile_handle\x18\x03 \x01(\tR\rprofileHandle\x12!\n" +
	"\fprofile_name\x18\x04 \x01(\tR\vprofileName\x121\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1b.yacycrawl.v1.CrawlRunStateR\x05state\x121\n" +
	"\x05tally\x18\x06 \x01(\v2\x1b.yacycrawl.v1.CrawlRunTallyR\x05tally\x12-\n" +
	"\x10pages_per_minute\x18\a \x01(\rH\x00R\x0epagesPerMinute\x88\x01\x01\x12\x19\n" +
	"\blease_id\x18\b \x01(\tR\aleaseId\x12*\n" +
	"\x11worker_session_id\x18\t \x01(\tR\x0fworkerSessionIdB\x13\n" +
	"\x11_pages_per_minute\"\x12\n" +
	"\x10CrawlProgressAck*\xb0\x02\n" +
	"\x10CrawlControlKind\x12\"\n" +
	"\x1eCRAWL_CONTROL_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CRAWL_CONTROL_KIND_PAUSE\x10\x01\x12\x1d\n" +
	"\x19CRAWL_CONTROL_KIND_RESUME\x10\x02\x12\x1d\n" +
	"\x19CRAWL_CONTROL_KIND_CANCEL\x10\x03\x12\x1f\n" +
	"\x1bCRAWL_CONTROL_KIND_SET_RATE\x10\x04\x12\x1e\n" +
	"\x1aCRAWL_CONTROL_KIND_RESTART\x10\x05\x12\"\n" +
	"\x1eCRAWL_CONTROL_KIND_SET_WORKERS\x10\x06\x127\n" +
	"3CRAWL_CONTROL_KIND_SET_AUTOMATIC_DISCOVERY_PRIORITY\x10\a*\x8a\x01\n" +
	"\rCrawlRunState\x12\x1f\n" +
	"\x1bCRAWL_RUN_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CRAWL_RUN_STATE_RUNNING\x10\x01\x12\x1c\n" +
	"\x18CRAWL_RUN_STATE_FINISHED\x10\x02\x12\x1d\n" +
	"\x19CRAWL_RUN_STATE_CANCELLED\x10\x032\x97\x03\n" +
	"\rCrawlExchange\x12S\n" +
	"\fStreamOrders\x12 .yacycrawl.v1.WorkerRegistration\x1a\x1f.yacycrawl.v1.CrawlOrderMessage0\x01\x12@\n" +
	"\bAckOrder\x12\x16.yacycrawl.v1.OrderAck\x1a\x1c.yacycrawl.v1.OrderAckResult\x12O\n" +
	"\tHeartbeat\x12\x1d.yacycrawl.v1.WorkerHeartbeat\x1a#.yacycrawl.v1.WorkerHeartbeatResult\x12I\n" +
	"\fSubmitIngest\x12 .yacycrawl.v1.IngestBatchMessage\x1a\x17.yacycrawl.v1.IngestAck\x12S\n" +
	"\x0eReportProgress\x12!.yacycrawl.v1.CrawlProgressReport\x1a\x1e.yacycrawl.v1.CrawlProgressAckB2Z0github.com/D4rk4/yago/yagocrawlcontract/crawlrpcb\x06proto3"

var (
	file_crawlexchange_proto_rawDescOnce sync.Once
	file_crawlexchange_proto_rawDescData []byte
)

func file_crawlexchange_proto_rawDescGZIP() []byte {
	file_crawlexchange_proto_rawDescOnce.Do(func() {
		file_crawlexchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crawlexchange_proto_rawDesc), len(file_crawlexchange_proto_rawDesc)))
	})
	return file_crawlexchange_proto_rawDescData
}

var file_crawlexchange_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crawlexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_crawlexchange_proto_goTypes = []any{
	(CrawlControlKind)(0),         // 0: yacycrawl.v1.CrawlControlKind
	(CrawlRunState)(0),            // 1: yacycrawl.v1.CrawlRunState
	(*WorkerRegistration)(nil),    // 2: yacycrawl.v1.WorkerRegistration
	(*CrawlOrderMessage)(nil),     // 3: yacycrawl.v1.CrawlOrderMessage
	(*OrderAck)(nil),              // 4: yacycrawl.v1.OrderAck
	(*OrderAckResult)(nil),        // 5: yacycrawl.v1.OrderAckResult
	(*WorkerHeartbeat)(nil),       // 6: yacycrawl.v1.WorkerHeartbeat
	(*CrawlControlDirective)(nil), // 7: yacycrawl.v1.CrawlControlDirective
	(*WorkerHeartbeatResult)(nil), // 8: yacycrawl.v1.WorkerHeartbeatResult
	(*IngestBatchMessage)(nil),    // 9: yacycrawl.v1.IngestBatchMessage
	(*IngestAck)(nil),             // 10: yacycrawl.v1.IngestAck
	(*CrawlRunTally)(nil),         // 11: yacycrawl.v1.CrawlRunTally
	(*CrawlProgressReport)(nil),   // 12: yacycrawl.v1.CrawlProgressReport
	(*CrawlProgressAck)(nil),      // 13: yacycrawl.v1.CrawlProgressAck
}
var file_crawlexchange_proto_depIdxs = []int32{
	1,  // 0: yacycrawl.v1.OrderAck.terminal_state:type_name -> yacycrawl.v1.CrawlRunState
	11, // 1: yacycrawl.v1.OrderAck.terminal_tally:type_name -> yacycrawl.v1.CrawlRunTally
	0,  // 2: yacycrawl.v1.CrawlControlDirective.kind:type_name -> yacycrawl.v1.CrawlControlKind
	7,  // 3: yacycrawl.v1.WorkerHeartbeatResult.directives:type_name -> yacycrawl.v1.CrawlControlDirective
	1,  // 4: yacycrawl.v1.CrawlProgressReport.state:type_name -> yacycrawl.v1.CrawlRunState
	11, // 5: yacycrawl.v1.CrawlProgressReport.tally:type_name -> yacycrawl.v1.CrawlRunTally
	2,  // 6: yacycrawl.v1.CrawlExchange.StreamOrders:input_type -> yacycrawl.v1.WorkerRegistration
	4,  // 7: yacycrawl.v1.CrawlExchange.AckOrder:input_type -> yacycrawl.v1.OrderAck
	6,  // 8: yacycrawl.v1.CrawlExchange.Heartbeat:input_type -> yacycrawl.v1.WorkerHeartbeat
	9,  // 9: yacycrawl.v1.CrawlExchange.SubmitIngest:input_type -> yacycrawl.v1.IngestBatchMessage
	12, // 10: yacycrawl.v1.CrawlExchange.ReportProgress:input_type -> yacycrawl.v1.CrawlProgressReport
	3,  // 11: yacycrawl.v1.CrawlExchange.StreamOrders:output_type -> yacycrawl.v1.CrawlOrderMessage
	5,  // 12: yacycrawl.v1.CrawlExchange.AckOrder:output_type -> yacycrawl.v1.OrderAckResult
	8,  // 13: yacycrawl.v1.CrawlExchange.Heartbeat:output_type -> yacycrawl.v1.WorkerHeartbeatResult
	10, // 14: yacycrawl.v1.CrawlExchange.SubmitIngest:output_type -> yacycrawl.v1.IngestAck
	13, // 15: yacycrawl.v1.CrawlExchange.ReportProgress:output_type -> yacycrawl.v1.CrawlProgressAck
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_crawlexchange_proto_init() }
func file_crawlexchange_proto_init() {
	if File_crawlexchange_proto != nil {
		return
	}
	file_crawlexchange_proto_msgTypes[2].OneofWrappers = []any{}
	file_crawlexchange_proto_msgTypes[4].OneofWrappers = []any{}
	file_crawlexchange_proto_msgTypes[6].OneofWrappers = []any{}
	file_crawlexchange_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crawlexchange_proto_rawDesc), len(file_crawlexchange_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crawlexchange_proto_goTypes,
		DependencyIndexes: file_crawlexchange_proto_depIdxs,
		EnumInfos:         file_crawlexchange_proto_enumTypes,
		MessageInfos:      file_crawlexchange_proto_msgTypes,
	}.Build()
	File_crawlexchange_proto = out.File
	file_crawlexchange_proto_goTypes = nil
	file_crawlexchange_proto_depIdxs = nil
}
