version: 3
workdir: .

allow:
  depOnAnyVendor: false
  deepScan: false

components:
  yagocrawlcontract:
    in:
      - .
      - "**"

vendors:
  yagomodel:
    in:
      - github.com/D4rk4/yago/yagomodel
      - github.com/D4rk4/yago/yagomodel/**
  grpc:
    in:
      - google.golang.org/grpc
      - google.golang.org/grpc/**
  protobuf:
    in:
      - google.golang.org/protobuf
      - google.golang.org/protobuf/**

deps:
  yagocrawlcontract:
    mayDependOn:
      - yagocrawlcontract
    canUse:
      - yagomodel
      - grpc
      - protobuf
