package compatibility

var adminSurfaceSpecs = []surfaceSpec{
	{
		Name:     "Health",
		Path:     "/health",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Returns a successful status when the ops listener is running.",
		Evidence: []string{"yagonode/internal/yagonode/main_test.go"},
	},
	{
		Name:     "Readiness",
		Path:     "/ready",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Reports whether local node dependencies are ready to serve traffic, starting with the local search index.",
		Evidence: []string{"yagonode/internal/yagonode/readiness_endpoint_test.go"},
	},
	{
		Name:     "Admin authentication",
		Path:     "/api/admin/v1/auth/*",
		Methods:  []string{"GET", "POST"},
		State:    Implemented,
		Behavior: "Provides first-run admin setup, Argon2id-verified login issuing an HttpOnly SameSite=Strict session cookie plus a CSRF token, session introspection, and logout that invalidates the server-side session. Login is rate limited per client and a failed login does not reveal whether the account exists.",
		Evidence: []string{
			"yagonode/internal/adminauth/*_test.go",
			"yagonode/internal/yagonode/node_admin_auth_test.go",
		},
		Notes: "Every operations endpoint except /health and /ready requires a valid admin session or an API key with the scope for the path, and cookie-authenticated unsafe methods also require the CSRF token. Provision the admin with YAGO_ADMIN_USER and YAGO_ADMIN_PASSWORD, or POST /api/admin/v1/auth/setup on first run.",
	},
	{
		Name:     "Admin API keys",
		Path:     "/api/admin/v1/auth/api-keys",
		Methods:  []string{"GET", "POST", "DELETE"},
		State:    Implemented,
		Behavior: "Mints high-entropy API keys with explicit scopes, returning the secret once and storing only its SHA-256 hash with a public identifier, lists key metadata and last-used time without the secret, and revokes keys by identifier. A Bearer API key authenticates operations requests as an alternative to a session cookie and always authenticates the Tavily-compatible public API when its search scope matches. Scoped-only mode disables only the legacy static search token. Keys are rate limited per key and need no CSRF token.",
		Evidence: []string{
			"yagonode/internal/adminauth/api_key_store_test.go",
			"yagonode/internal/adminauth/api_key_endpoints_test.go",
			"yagonode/internal/adminauth/guard_apikey_test.go",
			"yagonode/internal/yagonode/node_tavily_scoped_auth_integration_test.go",
		},
		Notes: "Scopes are admin:read, admin:write, crawl:write, search:read, and search:raw; search scopes authorize the public Tavily-compatible API. Managing keys requires admin:write or a session.",
	},
	{
		Name:     "Metrics",
		Path:     "/metrics",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves Prometheus metrics for node operations, including admin_login_attempts_total and admin_api_key_auth_total counters labelled by result.",
		Evidence: []string{"yagonode/internal/metrics/*_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope; scrape with a session cookie or a Bearer API key, or bind the ops listener to a trusted network.",
	},
	{
		Name:     "Recent events",
		Path:     "/api/admin/v1/events",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves recent structured node events newest-first from a bounded in-memory ring, each with a UTC time, severity, category, name, and message; an optional limit query parameter bounds the count and a non-positive or non-numeric limit is rejected with 400.",
		Evidence: []string{
			"yagonode/internal/events/*_test.go",
			"yagonode/internal/yagonode/events_endpoint_test.go",
		},
		Notes: "Requires a valid admin session or an API key with the admin:read scope. Events are in-memory only and do not survive a restart. Security-category events cover admin login and API key auth outcomes without revealing credentials.",
	},
	{
		Name:     "DHT gate report",
		Path:     "/api/admin/v1/network/dht/gates",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves current outbound DHT gate state, configuration, and named gate results.",
		Evidence: []string{"yagonode/internal/yagonode/dht_gate_status_endpoint_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Search index stats",
		Path:     "/api/admin/v1/index/stats",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves current local search backend availability, backend name, document count, and last index update time.",
		Evidence: []string{"yagonode/internal/yagonode/index_stats_endpoint_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Search ranking explain",
		Path:     "/api/admin/v1/search/explain",
		Methods:  []string{"POST"},
		State:    Implemented,
		Behavior: "Explains a bounded local or global search query. Local scope accepts caller-supplied ranking weights; global scope shares the active local, peer, web, recovery, analyzer-evidence, and reciprocal-rank fusion path. Results include human-facing provenance, retrieval and final scores, structured fusion contributions, partial failures, learned signal and tree contributions, model identity, and final rank without saving a paging session, remote result, or crawl seed. Missing weights use the live profile; invalid weights or scope return 400.",
		Evidence: []string{
			"yagonode/internal/yagonode/search_explain_endpoint_test.go",
			"yagonode/internal/yagonode/search_explain_global_test.go",
		},
		Notes: "Requires a valid admin session with a CSRF token, or an API key with the search:read scope.",
	},
	{
		Name:     "Search ranking trusted domains",
		Path:     "/api/admin/v1/search/ranking/trust",
		Methods:  []string{"GET", "PUT"},
		State:    Implemented,
		Behavior: "Reads or atomically replaces the bounded operator-curated trusted-domain policy used by domain authority.",
		Evidence: []string{
			"yagonode/internal/hosttrust/*_test.go",
			"yagonode/internal/yagonode/search_host_trust_endpoint_test.go",
		},
		Notes: "GET requires an admin session or admin:read API key. PUT requires a session with CSRF or an admin:write API key.",
	},
	{
		Name:     "Crawl dispatch",
		Path:     "/crawl",
		Methods:  []string{"POST"},
		State:    Partial,
		Behavior: "Publishes local crawl orders when crawler integration is configured; supports url, sitemap, sitelist, and robots start modes, and validates the crawl profile before publishing so an impossible URL regex or an out-of-range depth, pages-per-host, or duration is rejected with 400.",
		Evidence: []string{
			"yagonode/internal/crawldispatch/*_test.go",
			"yagonode/internal/yagonode/node_crawl_test.go",
		},
		Notes: "Mounted only when gRPC-backed crawling is configured; requires a valid admin session with a CSRF token, or an API key with the crawl:write scope.",
	},
	{
		Name:     "Compatibility report",
		Path:     "/api/admin/v1/compatibility",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves this machine-readable compatibility catalog.",
		Evidence: []string{
			"yagonode/internal/compatibility/*_test.go",
			"yagonode/internal/yagonode/compatibility_endpoint_test.go",
		},
		Notes: "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Java YaCy admin page clone set",
		Path:     "/*_p.html",
		Methods:  []string{"GET", "POST"},
		State:    Unsupported,
		Behavior: "Java YaCy administration pages are not cloned into the Go peer.",
		Notes:    "The project target is a Go admin API and Carbon UI rather than Java servlet page parity.",
	},
}
