package compatibility

var adminSurfaceSpecs = []surfaceSpec{
	{
		Name:     "Health",
		Path:     "/health",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Returns a successful status when the ops listener is running.",
		Evidence: []string{"yacynode/internal/yagonode/main_test.go"},
	},
	{
		Name:     "Readiness",
		Path:     "/ready",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Reports whether local node dependencies are ready to serve traffic, starting with the local search index.",
		Evidence: []string{"yacynode/internal/yagonode/readiness_endpoint_test.go"},
	},
	{
		Name:     "Admin authentication",
		Path:     "/api/admin/v1/auth/*",
		Methods:  []string{"GET", "POST"},
		State:    Implemented,
		Behavior: "Provides first-run admin setup, Argon2id-verified login issuing an HttpOnly SameSite=Strict session cookie plus a CSRF token, session introspection, and logout that invalidates the server-side session. Login is rate limited per client and a failed login does not reveal whether the account exists.",
		Evidence: []string{
			"yacynode/internal/adminauth/*_test.go",
			"yacynode/internal/yagonode/node_admin_auth_test.go",
		},
		Notes: "Every operations endpoint except /health and /ready requires a valid admin session or an API key with the scope for the path, and cookie-authenticated unsafe methods also require the CSRF token. Provision the admin with YAGO_ADMIN_USER and YAGO_ADMIN_PASSWORD, or POST /api/admin/v1/auth/setup on first run.",
	},
	{
		Name:     "Admin API keys",
		Path:     "/api/admin/v1/auth/api-keys",
		Methods:  []string{"GET", "POST", "DELETE"},
		State:    Implemented,
		Behavior: "Mints high-entropy API keys with explicit scopes, returning the secret once and storing only its SHA-256 hash with a public identifier, lists key metadata and last-used time without the secret, and revokes keys by identifier. A Bearer API key authenticates operations requests as an alternative to a session cookie, is checked against the scope required for the path, is rate limited per key, and needs no CSRF token.",
		Evidence: []string{
			"yacynode/internal/adminauth/api_key_store_test.go",
			"yacynode/internal/adminauth/api_key_endpoints_test.go",
			"yacynode/internal/adminauth/guard_apikey_test.go",
		},
		Notes: "Scopes are admin:read, admin:write, crawl:write, search:read, and search:raw; search scopes are reserved for the public search API. Managing keys requires admin:write or a session.",
	},
	{
		Name:     "Metrics",
		Path:     "/metrics",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves Prometheus metrics for node operations.",
		Evidence: []string{"yacynode/internal/metrics/*_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope; scrape with a session cookie or a Bearer API key, or bind the ops listener to a trusted network.",
	},
	{
		Name:     "DHT gate report",
		Path:     "/api/admin/v1/network/dht/gates",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves current outbound DHT gate state, configuration, and named gate results.",
		Evidence: []string{"yacynode/internal/yagonode/dht_gate_status_endpoint_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Search index stats",
		Path:     "/api/admin/v1/index/stats",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves current local search backend availability, backend name, document count, and last index update time.",
		Evidence: []string{"yacynode/internal/yagonode/index_stats_endpoint_test.go"},
		Notes:    "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Crawl dispatch",
		Path:     "/crawl",
		Methods:  []string{"POST"},
		State:    Partial,
		Behavior: "Publishes local crawl orders when crawler integration is configured; supports url, sitemap, and sitelist start modes, and validates the crawl profile before publishing so an impossible URL regex or an out-of-range depth, pages-per-host, or duration is rejected with 400.",
		Evidence: []string{
			"yacynode/internal/crawldispatch/*_test.go",
			"yacynode/internal/yagonode/node_crawl_test.go",
		},
		Notes: "Mounted only when gRPC-backed crawling is configured; requires a valid admin session with a CSRF token, or an API key with the crawl:write scope.",
	},
	{
		Name:     "Compatibility report",
		Path:     "/api/admin/v1/compatibility",
		Methods:  []string{"GET"},
		State:    Implemented,
		Behavior: "Serves this machine-readable compatibility catalog.",
		Evidence: []string{
			"yacynode/internal/compatibility/*_test.go",
			"yacynode/internal/yagonode/compatibility_endpoint_test.go",
		},
		Notes: "Requires a valid admin session or an API key with the admin:read scope.",
	},
	{
		Name:     "Java YaCy admin page clone set",
		Path:     "/*_p.html",
		Methods:  []string{"GET", "POST"},
		State:    Unsupported,
		Behavior: "Java YaCy administration pages are not cloned into the Go peer.",
		Notes:    "The project target is a Go admin API and Carbon UI rather than Java servlet page parity.",
	},
}
